name: CI

on:
    pull_request:
        branches: ["**"]
    push:
        branches: ["main", "master"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Install dependencies
              run: npm install

            - name: Lint
              run: npm run lint

            - name: Prettier check
              run: npm run format:check

            - name: Type-check
              run: npm run build --if-present
              env:
                  PULUMI_SKIP_UPDATE_CHECK: "true"

            - name: Run unit tests
              run: npm test
              env:
                  PULUMI_SKIP_UPDATE_CHECK: "true"
